// This file is automatically generated by Firebase Studio.
// Do not edit manually.

// To change the Firebase project, use the "Change Firebase Project" command.
// To trigger a re-generation of this file, exit and re-enter the workspace.

// 🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
//
// This file is used to load the Firebase config from the server. It is not
// intended to be used directly. Instead, use the `initializeFirebase` function
// in `src/firebase/index.ts`.
//
// 🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

let promise: Promise<any>;

/**
 * This needs to be a promise because the firebase config is not available
 * at build time. It is fetched from the server at runtime.
 */
export async function getFirebaseConfig() {
  if (promise) {
    return promise;
  }
  // This is a special placeholder that will be replaced by the server with the
  // actual Firebase config.
  // DO NOT REMOVE THIS COMMENT BLOCK
  /* __FIREBASE_CONFIG__ */
  const config = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;
  if (config) {
    promise = Promise.resolve(JSON.parse(config));
  } else {
    promise = fetch('/__firebase/config').then(res => res.json());
  }

  return promise;
}
