
// This file is automatically generated by Firebase Studio.
// Do not edit manually.

let promise: Promise<any>;

/**
 * This needs to be a promise because the firebase config is not available
 * at build time. It is fetched from the server at runtime.
 */
export async function getFirebaseConfig() {
  if (promise) {
    return promise;
  }

  // First try: Environment Variable (usually set in Firebase Studio)
  const configEnv = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;
  if (configEnv) {
    try {
      const parsed = JSON.parse(configEnv);
      if (parsed && parsed.apiKey) {
        console.log("Firebase config loaded from environment variable.");
        promise = Promise.resolve(parsed);
        return promise;
      }
    } catch (e) {
      console.error("Failed to parse NEXT_PUBLIC_FIREBASE_CONFIG env var", e);
    }
  }

  // Second try: Fetch from the local proxy endpoint
  console.log("Fetching Firebase config from /__firebase/config...");
  promise = fetch('/__firebase/config')
    .then(async (res) => {
      if (!res.ok) {
        throw new Error(`Konfigurations-Endpunkt nicht gefunden (Status ${res.status}). Bitte stelle sicher, dass das Firebase-Projekt in den Studio-Einstellungen verknüpft ist.`);
      }
      const contentType = res.headers.get('content-type');
      if (contentType && contentType.includes('application/json')) {
        return res.json();
      }
      throw new Error('Der Konfigurations-Endpunkt hat kein gültiges JSON zurückgegeben.');
    })
    .catch((err) => {
      console.error("Error loading Firebase config:", err);
      throw err;
    });

  return promise;
}
