
// This file is automatically generated by Firebase Studio.
// Do not edit manually.

let promise: Promise<any>;

/**
 * This needs to be a promise because the firebase config is not available
 * at build time. It is fetched from the server at runtime.
 */
export async function getFirebaseConfig() {
  if (promise) {
    return promise;
  }

  const config = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;
  if (config) {
    try {
      promise = Promise.resolve(JSON.parse(config));
      return promise;
    } catch (e) {
      console.error("Failed to parse NEXT_PUBLIC_FIREBASE_CONFIG", e);
    }
  }

  promise = fetch('/__firebase/config')
    .then(async (res) => {
      if (!res.ok) {
        throw new Error(`Failed to fetch Firebase config: ${res.status} ${res.statusText}`);
      }
      const contentType = res.headers.get('content-type');
      if (contentType && contentType.includes('application/json')) {
        return res.json();
      }
      const text = await res.text();
      console.error("Received non-JSON response from config endpoint:", text.substring(0, 100));
      throw new Error('Firebase config endpoint did not return JSON. Please check if Firebase is correctly configured.');
    })
    .catch((err) => {
      console.error("Error loading Firebase config:", err);
      throw err;
    });

  return promise;
}
